apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: k8s-management
  sources:
  - repoURL: 'https://github.com/ClubCedille/k8s-management.git'
    path: system/vault-configs
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
