apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system/argocd/
#- git@github.com:ClubCedille/k8s-base.git/bases/common/

  # This patch sets common settings for Applications.
patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: not-used
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      syncPolicy:
        automated:
          selfHeal: true
  target:
    kind: Application
