apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv
spec:
  authentication: 
    path: k8s-management
    role: config-admin
  type: kv
---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: kv-system
spec:
  authentication: 
    path: k8s-management
    role: config-admin
  type: kv