apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  virtualhost:
    fqdn: argocd.mgmt.cedille.club
    tls:
      secretName: argocd-tls
      enableRedirect: true
  routes:
    - conditions:
        - prefix: /
      services:
        - name: argocd-server
          port: 80
      enableWebsockets: true
