apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vault
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  virtualhost:
    fqdn: vault.mgmt.cedille.club
    # tls:
    #   secretName: vault-tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: vault
          port: 8200
      enableWebsockets: true
