apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: k8s-management
  sources:
  - repoURL: 'https://github.com/ClubCedille/k8s-management.git'
    path: system/vault
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
