apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "management"
      source:
        repoURL: https://github.com/ClubCedille/k8s-management/
        targetRevision: HEAD
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: management
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
