apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusterset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: "management"
      source:
        repoURL: https://github.com/ClubCedille/k8s-management/
        targetRevision: HEAD
        path: system/argocd/argoset
        kustomize:
          patches:
            - patch: |-
                - op: replace
                  path: /metadata/name
                  value: '{{.name}}'
                - op: replace
                  path: /spec/destinations/0/server
                  value: '{{.server}}'
              target:
                kind: AppProject
      destination:
        server: https://kubernetes.default.svc
        namespace: management
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
