apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
spec:
  metadata:
    name: base
  spec:
    project: "k8s-management"
    source:
      repoURL: https://github.com/ClubCedille/k8s-base/
      targetRevision: HEAD
      path: .
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
